### ISSUE TITLE
Homepage in Gemspec is incorrect

### ISSUE THREAD

**Issue by cew821** [davetron5000/trickster#11]
The `Gemspec` file lists the homepage as `http://your.website.com/` instead of the correct `https://github.com/davetron5000/trickster`. Not such a big deal, except the RubyGems page for the gem (which has highest SEO in the search I made for it) links to website.com instead of to this awesome gem!

**Comment by davetron5000** [comment]
Thank you!  I didn't notice that at all. Should be fixed now.
